// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDotnetPostgresApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace my_dotnet_postgres_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250227120712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyDotnetPostgresApi.Models.CorreoElectronico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonaDocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonaDocumentoIdentidad");

                    b.ToTable("CorreosElectronicos");
                });

            modelBuilder.Entity("MyDotnetPostgresApi.Models.DireccionFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonaDocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonaDocumentoIdentidad");

                    b.ToTable("DireccionesFisicas");
                });

            modelBuilder.Entity("MyDotnetPostgresApi.Models.NumeroTelefonico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonaDocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonaDocumentoIdentidad");

                    b.ToTable("NumerosTelefonicos");
                });

            modelBuilder.Entity("MyDotnetPostgresApi.Models.Persona", b =>
                {
                    b.Property<string>("DocumentoIdentidad")
                        .HasColumnType("text");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentoIdentidad");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("MyDotnetPostgresApi.Models.CorreoElectronico", b =>
                {
                    b.HasOne("MyDotnetPostgresApi.Models.Persona", "Persona")
                        .WithMany("CorreosElectronicos")
                        .HasForeignKey("PersonaDocumentoIdentidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("MyDotnetPostgresApi.Models.DireccionFisica", b =>
                {
                    b.HasOne("MyDotnetPostgresApi.Models.Persona", "Persona")
                        .WithMany("DireccionesFisicas")
                        .HasForeignKey("PersonaDocumentoIdentidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("MyDotnetPostgresApi.Models.NumeroTelefonico", b =>
                {
                    b.HasOne("MyDotnetPostgresApi.Models.Persona", "Persona")
                        .WithMany("NumerosTelefonicos")
                        .HasForeignKey("PersonaDocumentoIdentidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("MyDotnetPostgresApi.Models.Persona", b =>
                {
                    b.Navigation("CorreosElectronicos");

                    b.Navigation("DireccionesFisicas");

                    b.Navigation("NumerosTelefonicos");
                });
#pragma warning restore 612, 618
        }
    }
}
